# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: facial_recognition_app
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"  # For Streamlit UI
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - OPENCV_VIDEOIO_PRIORITY_MSMF=0
    devices:
      - "/dev/video0:/dev/video0"  # For camera access
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=facial_recognition

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongodb_data:
